import './globals.css'
import { Inter } from 'next/font/google'
import '@picocss/pico'
import UnderConstruct from './underConstruct'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function App({ Component, pageProps }) {
    return <Component {...pageProps} />;
  }

//  export default function App({ Component, pageProps }) {
//    return <UnderConstruct/>;
//  }